name: speed_limits
delays: []
speed_limits:
  - start_station: jinanxi
    end_station: taian
    start_time: "08:00:00"
    duration: 7200
    limit_speed: 80
  - start_station: qufudong
    end_station: tengzhoudong
    start_time: "09:30:00"
    duration: 7200
    limit_speed: 120
